project:
  type: book
  output-dir: docs

book:
  title: "The Unjournal evaluations: data and analysis"
  author: "David Reinstein, Julia Bottesini, and the Unjournal team"
  repo-url: https://github.com/unjournal/unjournaldata/
  repo-actions: [edit, issue]
  reader-mode: true
  page-navigation: true
  date: today

execute:
  freeze: false # re-render only when source changes
  warning: false
  message: false
  error: true
  echo: false

comments:
    hypothesis: true
   #bibliography: references.bib

format:
  html:
    code-fold: false
    code-link: false #note: this isn't working for me
    code-tools: false
    theme: cosmo
    citations-hover: true
    footnotes-hover: true
    #css: styles.css

    # margin-right: 0.5em
    #  margin-left: 0.5em
    #  max-width: 3200px
 # pdf:
  #  documentclass: scrreprt
  #



