project:
  type: book
  output-dir: docs

book:
  title: "The Unjournal evaluations: data and analysis"
  author: "David Reinstein, Julia Bottesini, and the Unjournal team"
  repo-url: https://github.com/unjournal/unjournaldata/
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - chapters/evaluation-data-analysis.qmd
  reader-mode: true
  page-navigation: true
  date: today

execute:
  freeze: false
  warning: false
  message: false
  error: true
  echo: false

comments:
    hypothesis: true

format:
  html:
    code-fold: false
    code-link: false #note: this isn't working for me
    code-tools: false
    theme: cosmo
    citations-hover: true
    footnotes-hover: true