project:
  type: website

website:
  title: "The Unjournal.org Blog"
  description: "News and insights from The Unjournal"
  site-url: https://unjournal.github.io
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/unjournal/unjournaldata

format:
  html:
    theme: cosmo
    css: styles.css



