project:
  type: website

website:
  title: "The Unjournal Data Blog"
  description: "News and insights from The Unjournal"
  site-url: https://unjournal.github.io
  repo-url: https://github.com/unjournal/unjournaldata/
  reader-mode: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/unjournal/unjournaldata

format:
  html:
    theme: cosmo
    css: styles.css
    code-fold: false
    code-link: false
    code-tools: false
    citations-hover: true
    footnotes-hover: true


