on:
  push:
    branches:
      - main

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions: 
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
          
      - name: Install system dependencies
        run: |
          sudo apt-get install jags libcurl4-openssl-dev \
            libharfbuzz-dev libfribidi-dev libsodium-dev

      - name: Setup dependencies with renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Import Unjournal data
        run: Rscript -e 'source("code/import-unjournal-data.R"); save_data()'
        env: 
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

      - name: Upload Unjournal data
        uses: actions/upload-artifact@v4
        with:
          name: unjournal-data
          path: data
          
      - name: Publish dashboard to shinyapps.io
        env:
          RSCONNECT_USER: ${{ secrets.RSCONNECT_USER }}
          RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
          RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
        run: |
          rsconnect::setAccountInfo(name = Sys.getenv("RSCONNECT_USER"), 
                                    token = Sys.getenv("RSCONNECT_TOKEN"),
                                    secret = Sys.getenv("RSCONNECT_SECRET"))
          quarto::quarto_publish_app(input = "shinyapp/dashboard", 
                                     account = "unjournal", 
                                     server = "shinyapps.io")
        shell: Rscript {0}
        
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

